//+------------------------------------------------------------------+
//|                                              ExecutionEngine.mqh |
//|                                  Copyright 2025, FUNDED AI EA    |
//|                                     https://www.fundedai-ea.com  |
//+------------------------------------------------------------------+
#property copyright "Copyright 2025, FUNDED AI EA"
#property link      "https://www.fundedai-ea.com"
#property strict

#include <Trade\Trade.mqh>
#include "../Core/Constants.mqh"
#include "../Core/Types.mqh"
#include "../Utils/SymbolUtils.mqh"

//+------------------------------------------------------------------+
//| Enumeration: Execution Status Classification                      |
//+------------------------------------------------------------------+
enum ENUM_EXECUTION_STATUS
  {
   EXEC_STATUS_EXECUTED             = 1, // Order fully filled
   EXEC_STATUS_PARTIALLY_EXECUTED   = 2, // Order partially filled
   EXEC_STATUS_REJECTED             = 3, // Order rejected by server
   EXEC_STATUS_CANCELLED            = 4, // Order cancelled
   EXEC_STATUS_AMBIGUOUS_RECONCILE  = 5  // Execution status ambiguous, reconciliation required
  };

//+------------------------------------------------------------------+
//| Struct: Order Execution Result Details                           |
//+------------------------------------------------------------------+
struct SExecutionResult
  {
   bool                  isSuccess;          // True if order placed/closed successfully
   ENUM_EXECUTION_STATUS execStatus;         // Explicit execution status
   ulong                 ticket;             // Position / Order Ticket Number
   ulong                 primaryDealTicket;  // Primary Reconciled Deal Ticket Number
   int                   totalDealsCount;    // Total deals generated by order
   double                executedPrice;      // Weighted-Average Filled Execution Price
   double                executedLot;        // Summed Filled Lot Size
   uint                  retcode;            // MT5 Trade Server Return Code
   string                errorMessage;       // Human-readable error description
  };

//+------------------------------------------------------------------+
//| Class CExecutionEngine                                           |
//| Native MQL5 Order Execution Engine handling trade sending,      |
//| multi-deal execution reconciliation, idempotency, retries.       |
//+------------------------------------------------------------------+
class CExecutionEngine
  {
private:
   CTrade   m_trade;
   ulong    m_magicNumber;
   int      m_maxSlippagePoints;
   int      m_maxRetries;

public:
                     CExecutionEngine(void);
                    ~CExecutionEngine(void);

   void              Init(ulong magicNumber, int maxSlippagePoints = 10, int maxRetries = 3);

   //--- Execution Methods
   SExecutionResult  OpenMarketOrder(string symbol, ENUM_ORDER_TYPE orderType, double lotSize, double stopLoss, double takeProfit, string comment = "");
   bool              ClosePositionByTicket(ulong ticket);
   bool              CloseAllPositions(string symbol = "");

   //--- Multi-Deal Reconciliation
   bool              ReconcileOrderMultiDeals(ulong orderTicket, ulong &primaryDealTicket, double &weightedAvgPrice, double &totalVolume, int &dealsCount);

   //--- Error Handler
   static string     GetRetcodeDescription(uint retcode);
   static bool       IsRetryableError(uint retcode);

private:
   ENUM_ORDER_TYPE_FILLING GetOptimalFillingType(string symbol);
  };

//+------------------------------------------------------------------+
//| Constructor                                                      |
//+------------------------------------------------------------------+
CExecutionEngine::CExecutionEngine(void)
  : m_magicNumber(FUNDED_AI_DEFAULT_MAGIC),
    m_maxSlippagePoints(DEFAULT_MAX_SLIPPAGE),
    m_maxRetries(3)
  {
   Init(FUNDED_AI_DEFAULT_MAGIC, DEFAULT_MAX_SLIPPAGE, 3);
  }

//+------------------------------------------------------------------+
//| Destructor                                                       |
//+------------------------------------------------------------------+
CExecutionEngine::~CExecutionEngine(void)
  {
  }

//+------------------------------------------------------------------+
//| Initializes trade settings                                       |
//+------------------------------------------------------------------+
void CExecutionEngine::Init(ulong magicNumber, int maxSlippagePoints, int maxRetries)
  {
   m_magicNumber       = magicNumber;
   m_maxSlippagePoints = maxSlippagePoints;
   m_maxRetries        = maxRetries;

   m_trade.SetExpertMagicNumber(m_magicNumber);
   m_trade.SetDeviationInPoints(m_maxSlippagePoints);
  }

//+------------------------------------------------------------------+
//| Auto-detects supported filling mode for broker symbol            |
//+------------------------------------------------------------------+
ENUM_ORDER_TYPE_FILLING CExecutionEngine::GetOptimalFillingType(string symbol)
  {
   uint fillingMode = (uint)SymbolInfoInteger(symbol, SYMBOL_FILLING_MODE);
   if((fillingMode & SYMBOL_FILLING_FOK) != 0)
      return ORDER_FILLING_FOK;
   if((fillingMode & SYMBOL_FILLING_IOC) != 0)
      return ORDER_FILLING_IOC;
   return ORDER_FILLING_RETURN;
  }

//+------------------------------------------------------------------+
//| Reconciles order execution across ALL deals for partial fills    |
//| Calculates weighted-average price & total executed volume        |
//+------------------------------------------------------------------+
bool CExecutionEngine::ReconcileOrderMultiDeals(ulong orderTicket, ulong &primaryDealTicket, double &weightedAvgPrice, double &totalVolume, int &dealsCount)
  {
   primaryDealTicket = 0;
   weightedAvgPrice  = 0.0;
   totalVolume       = 0.0;
   dealsCount        = 0;

   if(!HistorySelect(TimeCurrent() - 120, TimeCurrent() + 5))
      return false;

   double volumePriceSum = 0.0;
   int totalDeals = HistoryDealsTotal();

   for(int i = 0; i < totalDeals; i++)
     {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket > 0)
        {
         if(HistoryDealGetInteger(ticket, DEAL_ORDER) == (long)orderTicket)
           {
            if(primaryDealTicket == 0)
               primaryDealTicket = ticket;

            double dealPrice = HistoryDealGetDouble(ticket, DEAL_PRICE);
            double dealVol   = HistoryDealGetDouble(ticket, DEAL_VOLUME);

            volumePriceSum += (dealPrice * dealVol);
            totalVolume    += dealVol;
            dealsCount++;
           }
        }
     }

   if(dealsCount > 0 && totalVolume > 0.0)
     {
      weightedAvgPrice = volumePriceSum / totalVolume;
      return true;
     }

   return false;
  }

//+------------------------------------------------------------------+
//| Checks whether trade server error is retryable                   |
//+------------------------------------------------------------------+
bool CExecutionEngine::IsRetryableError(uint retcode)
  {
   if(retcode == TRADE_RETCODE_REQUOTE ||
      retcode == TRADE_RETCODE_PRICE_OFF ||
      retcode == TRADE_RETCODE_PRICE_CHANGED ||
      retcode == TRADE_RETCODE_TIMEOUT ||
      retcode == TRADE_RETCODE_TOO_MANY_REQUESTS)
      return true;
   return false;
  }

//+------------------------------------------------------------------+
//| Executes a market order with multi-deal reconciliation & retries |
//+------------------------------------------------------------------+
SExecutionResult CExecutionEngine::OpenMarketOrder(string symbol, ENUM_ORDER_TYPE orderType, double lotSize, double stopLoss, double takeProfit, string comment)
  {
   SExecutionResult result;
   result.isSuccess          = false;
   result.execStatus         = EXEC_STATUS_REJECTED;
   result.ticket             = 0;
   result.primaryDealTicket  = 0;
   result.totalDealsCount    = 0;
   result.executedPrice      = 0.0;
   result.executedLot        = 0.0;
   result.retcode            = 0;
   result.errorMessage       = "";

   if(lotSize <= 0.0)
     {
      result.errorMessage = "INVALID LOT SIZE: Calculated volume <= 0";
      return result;
     }

   SSymbolSpecification spec;
   if(!CSymbolUtils::GetSymbolSpec(symbol, spec, 10))
     {
      result.errorMessage = "SYMBOL ERROR: Could not fetch symbol specs";
      return result;
     }

   if(!spec.isTradeAllowed)
     {
      result.errorMessage = "TRADE BLOCKED: Broker disabled trading for symbol";
      return result;
     }

   m_trade.SetTypeFilling(GetOptimalFillingType(symbol));

   for(int attempt = 1; attempt <= m_maxRetries; attempt++)
     {
      bool success = false;
      if(orderType == ORDER_TYPE_BUY)
         success = m_trade.Buy(lotSize, symbol, 0.0, stopLoss, takeProfit, comment);
      else if(orderType == ORDER_TYPE_SELL)
         success = m_trade.Sell(lotSize, symbol, 0.0, stopLoss, takeProfit, comment);

      result.retcode = m_trade.ResultRetcode();

      if(success && result.retcode == TRADE_RETCODE_DONE)
        {
         result.ticket        = m_trade.ResultOrder();
         result.executedPrice = m_trade.ResultPrice();
         result.executedLot   = m_trade.ResultVolume();

         // Multi-deal reconciliation across history
         ulong primaryDeal = 0;
         double wAvgPrice = 0.0, sumVol = 0.0;
         int dCount = 0;

         if(ReconcileOrderMultiDeals(result.ticket, primaryDeal, wAvgPrice, sumVol, dCount))
           {
            result.primaryDealTicket = primaryDeal;
            result.totalDealsCount   = dCount;
            result.executedPrice     = wAvgPrice;
            result.executedLot       = sumVol;

            if(sumVol >= lotSize - 0.0001)
              {
               result.isSuccess    = true;
               result.execStatus   = EXEC_STATUS_EXECUTED;
               result.errorMessage = "ORDER EXECUTED FULLY";
              }
            else
              {
               result.isSuccess    = true;
               result.execStatus   = EXEC_STATUS_PARTIALLY_EXECUTED;
               result.errorMessage = StringFormat("PARTIAL FILL EXECUTED: Filled %.2f of %.2f lots across %d deals", sumVol, lotSize, dCount);
              }
           }
         else
           {
            // Ambiguous execution state - order returned DONE but deals not immediately found
            result.isSuccess    = false;
            result.execStatus   = EXEC_STATUS_AMBIGUOUS_RECONCILE;
            result.errorMessage = "AMBIGUOUS EXECUTION: Order done but deal history reconciliation pending";
           }

         return result;
        }

      result.execStatus   = EXEC_STATUS_REJECTED;
      result.errorMessage = StringFormat("Attempt %d failed: %s (Code: %u)", attempt, GetRetcodeDescription(result.retcode), result.retcode);

      // Do not retry non-retryable errors
      if(!IsRetryableError(result.retcode))
         break;

      Sleep(200 * attempt);
     }

   return result;
  }

//+------------------------------------------------------------------+
//| Closes position by ticket                                        |
//+------------------------------------------------------------------+
bool CExecutionEngine::ClosePositionByTicket(ulong ticket)
  {
   return m_trade.PositionClose(ticket);
  }

//+------------------------------------------------------------------+
//| Account-Wide Emergency Liquidator: Closes all open EA positions  |
//+------------------------------------------------------------------+
bool CExecutionEngine::CloseAllPositions(string symbol)
  {
   bool allClosed = true;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket > 0)
        {
         if(PositionGetInteger(POSITION_MAGIC) == (long)m_magicNumber)
           {
            if(symbol == "" || PositionGetString(POSITION_SYMBOL) == symbol)
              {
               if(!m_trade.PositionClose(ticket))
                  allClosed = false;
              }
           }
        }
     }
   return allClosed;
  }

//+------------------------------------------------------------------+
//| Translates MT5 trade return code into descriptive string          |
//+------------------------------------------------------------------+
string CExecutionEngine::GetRetcodeDescription(uint retcode)
  {
   switch(retcode)
     {
      case TRADE_RETCODE_DONE:             return "Trade done";
      case TRADE_RETCODE_REJECT:           return "Request rejected";
      case TRADE_RETCODE_CANCEL:           return "Request canceled";
      case TRADE_RETCODE_PLACED:           return "Order placed";
      case TRADE_RETCODE_ERROR:            return "Common error";
      case TRADE_RETCODE_TIMEOUT:          return "Request timeout";
      case TRADE_RETCODE_INVALID:          return "Invalid request";
      case TRADE_RETCODE_INVALID_VOLUME:   return "Invalid volume";
      case TRADE_RETCODE_INVALID_PRICE:    return "Invalid price";
      case TRADE_RETCODE_INVALID_STOPS:    return "Invalid stops";
      case TRADE_RETCODE_TRADE_DISABLED:   return "Trading disabled";
      case TRADE_RETCODE_MARKET_CLOSED:    return "Market closed";
      case TRADE_RETCODE_NO_MONEY:         return "Insufficient funds";
      case TRADE_RETCODE_PRICE_CHANGED:    return "Price changed";
      case TRADE_RETCODE_PRICE_OFF:        return "Off quotes";
      case TRADE_RETCODE_REQUOTE:          return "Requote";
      case TRADE_RETCODE_TOO_MANY_REQUESTS:return "Too many requests";
      default:                             return StringFormat("Unknown code %u", retcode);
     }
  }
